### ISSUE TITLE
plese help run start error app.useGlobalInterceptors(new StandardResponseInterceptor());

### ISSUE THREAD

**Issue by mycoms01** [miZyind/nestjs-demo#7]
import StandardResponseInterceptor
Argument of type 'StandardResponseInterceptor<any>' is not assignable to parameter of type 'NestInterceptor<any, any>'.
  The types returned by 'intercept(...)' are incompatible between these types.
    Type 'Observable<Result<any>>' is not assignable to type 'Observable<any> | Promise<Observable<any>>'.
      Type 'Observable<Result<any>>' is not assignable to type 'Observable<any>'.
        The types of 'source.operator.call' are incompatible between these types.
          Type '(subscriber: import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/nestjs-xion/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/nestjs-xion/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/rxjs/internal/types").TeardownLogic'.
            Types of parameters 'subscriber' and 'subscriber' are incompatible.
              Type 'import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/rxjs/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("/Users/sanit/Sites/Project/Devpers/P-NOI/OTEPC/APP/api/node_modules/nestjs-xion/node_modules/rxjs/internal/Subscriber").Subscriber<any>'.
                Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.ts(2345)

**Comment by miZyind** [comment]
Thanks for the report! I've fixed this problem. Please check it again.
